language: php

php:
 - 7.0
 - 7.1

before_script:
 - wget http://getcomposer.org/composer.phar
 - php composer.phar install --no-interaction

script:
 - cd tests; ./run.sh
 - cd ..; vendor/bin/phpunit

after_script:
 - php vendor/bin/coveralls -v