language: php

php:
 - 7.0
 - 7.1

before_script:
 - composer self-update
 - composer clear-cache
 - composer update

script:
 - cd tests; ./run.sh
 - cd ..; vendor/bin/phpunit
 - ./vendor/bin/phpcs --standard=PSR2 ./src/ ./tests/unitTests --config-set ignore_warnings_on_exit 1
 - ./vendor/bin/humbug

after_script:
 - php vendor/bin/coveralls -v